### ISSUE TITLE
[Информация] Пользователя и Регистрация

### ISSUE THREAD

**Issue by MaryMazel** [MaryMazel/KhSM#3]
Программа может работать без регистрации с ограниченной функциональностью. Любой человек может зарегистрироваться с помощью email и пароля. Обязательно потом ввод информации в профиле. Данные вносятся в базу данных.
  
Окно входа в приложение(логин и пароль), внизу кнопка регистрации, переход на новый экран с формой регистрации, подтверждение регистрации на почту.

Без регистрации человек может видеть результаты последней встречи, новости. Не может видеть свой профиль(его нет), рейтинг участников, соответственно его результатов нет.

Если зарегистрирован, но не прошел подтверждение админа, он не может участвовать во встречах, у него есть только свой профиль, не видит рейтинга.

**Comment by dmtrKovalenko** [comment]
:D

**Comment by maximzhemerenko** [comment]
@MaryMazel Пожалуйста, уточни, какие действия пользователь может совершать в программе, если
- Он не зарегистрирован еще
- Он зарегистрирован, но не прошел 'Approve' администратора

**Comment by maximzhemerenko** [comment]
Предлагаю следующую схему регистрации

- Пользователь создает учетную запись, вводя информацию о себе, такую как имя, фамилию итд + email, в системе создается пользователь, и на почту отправляется ссылка с предложением создать логин
- Администратор создает учетную запись, вводя информацию о пользователе, такую как имя, фамилию и email (не обязательно). Если email был указан, то на почту пользователя отправляется ссылка для создания логина.
- Когда пользователь активирует ссылку для создания логина, ему предлагается указать пароль. После этого он сможет заходить в приложение указав свой email и пароль.
- По умолчанию пользователь считается не подтвержденным. Администратор может разрешить данному пользователю участвовать в соревнованиях.
